Skelton
WhiteGyrfalcon/TEAMGAMMA pull request #3
Opened 2023-10-12 07:21 UTC by kresayuts05

Simple Skeleton

2023-10-12 07:27 UTC, Milena1199 approved these changes

2023-10-12 07:27 UTC, marielabelcheva approved these changes

2023-10-12 15:51 UTC, WhiteGyrfalcon requested changes

2023-10-12 15:51 UTC, WhiteGyrfalcon commented on .vs/TEAMGAMMA/FileContentIndex/5f9efc10-ba66-41a0-9003-e033a11e8f32.vsidx
Files from the .vs/ directory should not be uploaded to the repository. Same applies to the GamaGameHub/.vs/ directory. You should add both those directories to the .gitignore file (i think you didn't pull the repo before making these commits => you don't have the correct version of the project and the .gitignore file => you have uploaded the files). After having the correct .gitignore file git simply won't upload the specified directories and everything will be fine. Please make the necessary changes

2023-10-19 06:35 UTC, WhiteGyrfalcon approved these changes

2023-10-19 06:35 UTC, merged